const YOUTH_FOLLOW_KEY='ep-youth-followed-clubs';
const YOUTH_HOME_SCHOOL='贵州大学';
const YOUTH_CLUBS={
  creative:{name:'黔青创意社',school:'贵州大学',category:'文化艺术',logo:'黔',title:'2026秋季招新：寻找一起做校园设计的人',kind:'招新',time:'今天 09:30'},
  science:{name:'山野科学社',school:'贵州师范大学',category:'学术科技',logo:'山',title:'城市生态观察活动开放报名',kind:'活动动态',time:'昨天 16:20'},
  volunteer:{name:'微光志愿服务队',school:'贵州财经大学',category:'志愿公益',logo:'光',title:'社区阅读志愿者本周六集合',kind:'志愿招募',time:'2天前'}
};

function youthGo(route){route=String(route);if(parent!==window)parent.postMessage({educationPlusRoute:route},location.origin);else location.href=(/^[A-Z]/.test(String(window.EP_PAGE||''))?'../':'')+'index.html#'+route}
function youthToast(message){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';t.setAttribute('role','status');t.setAttribute('aria-live','polite');document.body.append(t)}t.textContent=message;t.classList.add('show');clearTimeout(window.__youthToast);window.__youthToast=setTimeout(()=>t.classList.remove('show'),1700)}
function switchYouthTab(name,button){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.pane').forEach(x=>x.hidden=x.dataset.pane!==name)}
function toggleAction(button,message){button.classList.toggle('on');youthToast(button.classList.contains('on')?message:'已取消')}
function filterYouthStatus(name,button){document.querySelectorAll('.status-tabs button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.status-card').forEach(x=>x.hidden=name!=='all'&&x.dataset.status!==name)}
function chooseContentType(button,type){document.querySelectorAll('.seg button').forEach(x=>x.classList.toggle('active',x===button));const input=document.getElementById('contentType');if(input)input.value=type;const upload=document.getElementById('uploadText');if(upload)upload.textContent=type==='短视频'?'选择视频文件（MP4，演示）':'选择图片（最多9张，演示）'}
function chooseYouthVisibility(button,visibility){button.closest('.seg').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===button));const input=document.getElementById('youthVisibility');if(input)input.value=visibility}
function submitYouthForm(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const record={status:'审核中',school:document.getElementById('youthSchool')?.value||'',visibility:document.getElementById('youthVisibility')?.value||'全部高校可见',title:document.getElementById('youthTitle')?.value||'',submittedAt:Date.now()};localStorage.setItem('ep-youth-demo-submitted',JSON.stringify(record));youthToast('提交成功，状态已更新为“审核中”');setTimeout(()=>youthGo('Y05'),700)}
function simulateUpload(){const label=document.getElementById('uploadText');if(label)label.textContent='已选择演示素材，可继续提交';youthToast('演示素材已选择')}

function setUniversityScope(scope,button){window.__universityScope=scope;document.querySelectorAll('[data-university-scope]').forEach(item=>item.classList.toggle('active',item===button));const school=document.getElementById('universitySchool');if(school){school.value=scope==='mine'?YOUTH_HOME_SCHOOL:'all';school.disabled=scope==='mine'}filterUniversityFeed()}
function filterUniversityFeed(){const school=document.getElementById('universitySchool');const selected=window.__universityScope==='mine'?YOUTH_HOME_SCHOOL:(school?.value||'all');let count=0;document.querySelectorAll('.university-card').forEach(card=>{const visible=selected==='all'||card.dataset.school===selected;card.hidden=!visible;if(visible)count++});const result=document.getElementById('universityResultCount');if(result)result.textContent=`${count}条校园创作`;const empty=document.getElementById('universityEmpty');if(empty)empty.hidden=count!==0}
function resetUniversityFilter(){window.__universityScope='all';document.querySelectorAll('[data-university-scope]').forEach(item=>item.classList.toggle('active',item.dataset.universityScope==='all'));const school=document.getElementById('universitySchool');if(school){school.disabled=false;school.value='all'}filterUniversityFeed()}

function readFollowedClubs(){try{return JSON.parse(localStorage.getItem(YOUTH_FOLLOW_KEY)||'[]').filter(id=>YOUTH_CLUBS[id])}catch{return[]}}
function saveFollowedClubs(ids){localStorage.setItem(YOUTH_FOLLOW_KEY,JSON.stringify([...new Set(ids)]))}
function updateFollowButton(button,isFollowing){if(!button)return;button.classList.toggle('following',isFollowing);button.setAttribute('aria-pressed',String(isFollowing));const detailed=Boolean(button.closest('.club-action-row'));button.textContent=isFollowing?'已关注':detailed?'关注社团':'关注'}
function hydrateFollowButtons(){const followed=readFollowedClubs();document.querySelectorAll('[data-follow-club]').forEach(button=>updateFollowButton(button,followed.includes(button.dataset.followClub)))}
function toggleClubFollow(clubId,button){const ids=readFollowedClubs();const index=ids.indexOf(clubId);let following;if(index>=0){ids.splice(index,1);following=false}else{ids.push(clubId);following=true}saveFollowedClubs(ids);document.querySelectorAll(`[data-follow-club="${clubId}"]`).forEach(item=>updateFollowButton(item,following));youthToast(following?'已关注，后续动态将进入关注动态':'已取消关注');if(window.EP_PAGE==='Y11')renderFollowingFeed()}
function filterClubs(){const keyword=(document.getElementById('clubSearch')?.value||'').trim().toLowerCase();const school=document.getElementById('clubSchoolFilter')?.value||'all';const category=document.getElementById('clubCategoryFilter')?.value||'all';let count=0;document.querySelectorAll('.club-card').forEach(card=>{const matchesKeyword=!keyword||(card.dataset.search||'').toLowerCase().includes(keyword);const matchesSchool=school==='all'||card.dataset.school===school;const matchesCategory=category==='all'||card.dataset.category===category;const visible=matchesKeyword&&matchesSchool&&matchesCategory;card.hidden=!visible;if(visible)count++});const result=document.getElementById('clubResultCount');if(result)result.textContent=`${count}个已认证社团`;const empty=document.getElementById('clubEmpty');if(empty)empty.hidden=count!==0}
function resetClubFilters(){const search=document.getElementById('clubSearch'),school=document.getElementById('clubSchoolFilter'),category=document.getElementById('clubCategoryFilter');if(search)search.value='';if(school)school.value='all';if(category)category.value='all';filterClubs()}

function simulateClubUpload(){const state=document.getElementById('clubUploadState');const label=document.getElementById('clubUploadText');if(state)state.value='selected';if(label)label.textContent='已选择社团证明材料（演示）';youthToast('演示材料已选择')}
function setClubOnboardingState(submitted){const tag=document.getElementById('clubStatusTag');const button=document.getElementById('clubSubmitButton');const hint=document.getElementById('clubReviewHint');if(tag){tag.textContent=submitted?'待线下核验':'未提交';tag.classList.toggle('yellow',submitted)}if(button){button.textContent=submitted?'已提交，等待线下核验':'提交入驻与认证申请';button.disabled=submitted}if(hint&&submitted)hint.textContent='平台将联系学校或指导教师核验身份；通过后绑定社团管理员。'}
function submitClubOnboarding(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const upload=document.getElementById('clubUploadState');if(!upload||!upload.value){youthToast('请先选择社团证明材料');document.getElementById('clubUpload')?.focus();return}const button=document.getElementById('clubSubmitButton');button.disabled=true;button.textContent='提交中…';setTimeout(()=>{localStorage.setItem('ep-youth-club-onboarding',JSON.stringify({status:'待线下核验',submittedAt:Date.now()}));setClubOnboardingState(true);youthToast('申请已提交，下一步为线下身份核验')},450)}

function filterClubUpdates(kind,button){button.closest('.tabs').querySelectorAll('.tab').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.club-update').forEach(card=>card.hidden=kind!=='all'&&card.dataset.updateKind!==kind)}
function chooseClubPostType(button,type){button.closest('.seg').querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));const input=document.getElementById('clubPostType');if(input)input.value=type}
function simulateClubPostUpload(){const label=document.getElementById('clubPostUploadText');if(label)label.textContent='已选择社团图片素材（演示）';youthToast('演示素材已选择')}
function submitClubPost(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const record={type:document.getElementById('clubPostType')?.value||'社团动态',title:document.getElementById('clubPostTitle')?.value||'新社团内容',body:document.getElementById('clubPostBody')?.value||'',submittedAt:Date.now()};localStorage.setItem('ep-youth-club-new-post',JSON.stringify(record));youthToast('内容已提交平台审核');setTimeout(()=>youthGo('Y09'),700)}
function hydrateClubAdmin(){const card=document.getElementById('clubNewPostCard');if(!card)return;try{const record=JSON.parse(localStorage.getItem('ep-youth-club-new-post')||'null');if(record){card.hidden=false;const title=document.getElementById('clubNewPostTitle');if(title)title.textContent=record.title}}catch{card.hidden=true}}
function renderFollowingFeed(){const feed=document.getElementById('followingFeed');const empty=document.getElementById('followingEmpty');if(!feed||!empty)return;feed.replaceChildren();const ids=readFollowedClubs();empty.hidden=ids.length!==0;ids.forEach(id=>{const club=YOUTH_CLUBS[id];const card=document.createElement('article');card.className='card following-card';const head=document.createElement('div');head.className='following-club';head.innerHTML=`<div class="club-logo">${club.logo}</div><div class="meta"><b>${club.name}</b><br>${club.school} · ${club.category}</div>`;const unfollow=document.createElement('button');unfollow.type='button';unfollow.className='unfollow-link';unfollow.textContent='取消关注';unfollow.dataset.followClub=id;unfollow.addEventListener('click',()=>toggleClubFollow(id,unfollow));head.append(unfollow);const tag=document.createElement('span');tag.className='tag';tag.textContent=club.kind;const title=document.createElement('div');title.className='title';title.textContent=club.title;const meta=document.createElement('div');meta.className='content-meta';meta.innerHTML=`<span>${club.time}</span><button class="follow-detail-link" type="button">查看社团主页</button>`;meta.querySelector('button').addEventListener('click',()=>youthGo('Y08'));card.append(head,tag,title,meta);feed.append(card)})}

document.addEventListener('DOMContentLoaded',()=>{hydrateFollowButtons();if(window.EP_PAGE==='Y01'){window.__universityScope='all';filterUniversityFeed()}if(window.EP_PAGE==='Y02')filterClubs();if(window.EP_PAGE==='Y07')setClubOnboardingState(Boolean(localStorage.getItem('ep-youth-club-onboarding')));if(window.EP_PAGE==='Y09')hydrateClubAdmin();if(window.EP_PAGE==='Y11')renderFollowingFeed()});
